export const INDIAN_BIKE_CATALOG: Record<string, string[]> = {
  'Royal Enfield': [
    'Classic 350',
    'Hunter 350',
    'Bullet 350',
    'Meteor 350',
    'Himalayan 450',
    'Guerrilla 450',
    'Continental GT 650',
    'Interceptor 650',
    'Super Meteor 650',
    'Shotgun 650',
    'Thunderbird 350',
    'Thunderbird 500',
    'Classic 500',
    'Bullet 500',
    'Himalayan 411',
    'Scram 411',
  ],
  'Yamaha': [
    'MT-15',
    'MT-15 V2',
    'R15 V4',
    'R15M',
    'R15 V3',
    'FZ-S FI',
    'FZ-S V4',
    'FZ FI',
    'FZ-X',
    'FZ25',
    'Aerox 155',
    'RayZR 125',
    'Fascino 125',
    'R3',
    'MT-03',
    'RX100',
    'RX135',
  ],
  'KTM': [
    '390 Duke',
    '250 Duke',
    '200 Duke',
    '125 Duke',
    'RC 390',
    'RC 200',
    'RC 125',
    '390 Adventure',
    '390 Adventure X',
    '250 Adventure',
  ],
  'TVS': [
    'Apache RTR 160 4V',
    'Apache RTR 160 2V',
    'Apache RTR 180',
    'Apache RTR 200 4V',
    'Apache RR 310',
    'Apache RTR 310',
    'Raider 125',
    'Ronin',
    'Jupiter 110',
    'Jupiter 125',
    'Ntorq 125',
    'iQube Electric',
    'Star City Plus',
    'Radeon',
    'Sport',
    'XL100',
    'Scooty Pep Plus',
    'Scooty Zest 110',
  ],
  'Bajaj': [
    'Pulsar 150',
    'Pulsar 125',
    'Pulsar N160',
    'Pulsar N150',
    'Pulsar NS200',
    'Pulsar NS160',
    'Pulsar NS125',
    'Pulsar N250',
    'Pulsar F250',
    'Pulsar RS200',
    'Pulsar 220F',
    'Pulsar NS400Z',
    'Dominar 400',
    'Dominar 250',
    'Avenger 220 Cruise',
    'Avenger 160 Street',
    'Platina 110',
    'Platina 100',
    'CT 110X',
    'CT 125X',
    'Chetak Electric',
    'Freedom 125 CNG',
    'Discover 125',
    'V15',
  ],
  'Honda': [
    'Activa 6G',
    'Activa 125',
    'Dio 110',
    'Dio 125',
    'Shine 125',
    'Shine 100',
    'SP 125',
    'SP 160',
    'Unicorn',
    'CB350 H\'ness',
    'CB350RS',
    'CB350',
    'CB300R',
    'CB300F',
    'Hornet 2.0',
    'X-Blade',
    'Livo',
    'CD 110 Dream',
    'Aviator',
    'Grazia',
    'CBR250R',
    'CBR150R',
  ],
  'Suzuki': [
    'Access 125',
    'Burgman Street',
    'Burgman Street EX',
    'Avenis 125',
    'Gixxer 150',
    'Gixxer SF 150',
    'Gixxer 250',
    'Gixxer SF 250',
    'V-Strom SX 250',
    'Hayabusa',
    'Intruder 150',
    'Katana',
  ],
  'Hero': [
    'Splendor Plus',
    'Splendor Plus XTEC',
    'Super Splendor',
    'Super Splendor XTEC',
    'HF Deluxe',
    'HF 100',
    'Passion Plus',
    'Passion Pro',
    'Passion XTEC',
    'Glamour',
    'Glamour XTEC',
    'Xtreme 125R',
    'Xtreme 160R 4V',
    'Xtreme 200S 4V',
    'XPulse 200 4V',
    'XPulse 200T 4V',
    'Karizma XMR 210',
    'Mavrick 440',
    'Pleasure Plus',
    'Destini 125',
    'Xoom 110',
    'Vida V1 Pro',
  ],
  'Kawasaki': [
    'Ninja 300',
    'Ninja 400',
    'Ninja 500',
    'Ninja 650',
    'Ninja ZX-4R',
    'Ninja ZX-6R',
    'Ninja ZX-10R',
    'Ninja 1000SX',
    'Z650',
    'Z900',
    'Versys 650',
    'Versys 1000',
    'Eliminator',
    'Vulcan S',
    'W175',
  ],
  'Jawa / Yezdi': [
    'Jawa 350',
    'Jawa 42',
    'Jawa 42 FJ',
    'Jawa Perak',
    'Jawa 42 Bobber',
    'Yezdi Roadster',
    'Yezdi Scrambler',
    'Yezdi Adventure',
  ],
  'Triumph': [
    'Speed 400',
    'Scrambler 400X',
    'Daytona 660',
    'Trident 660',
    'Tiger Sport 660',
    'Tiger 900',
    'Street Triple 765',
    'Bonneville T100',
    'Bonneville T120',
    'Bonneville Speedmaster',
  ],
  'Harley-Davidson': [
    'X440',
    'Iron 883',
    'Forty-Eight',
    'Street 750',
    'Street Rod 750',
    'Fat Boy',
    'Nightster',
    'Sportster S',
    'Pan America 1250',
  ],
  'BMW Motorrad': [
    'G 310 R',
    'G 310 GS',
    'G 310 RR',
    'F 900 R',
    'F 900 XR',
    'S 1000 RR',
    'S 1000 XR',
    'R 1250 GS',
    'R 1300 GS',
    'CE 02',
    'CE 04',
  ],
  'Ather Energy': [
    '450X',
    '450S',
    '450 Apex',
    'Rizta',
  ],
  'Ola Electric': [
    'S1 Pro Gen 2',
    'S1 Pro Gen 1',
    'S1 Air',
    'S1 X',
    'S1 X+',
    'Roadster',
  ],
  'Aprilia': [
    'RS 457',
    'SR 125',
    'SR 160',
    'Storm 125',
    'SXR 125',
    'SXR 160',
    'Tuono 660',
    'RS 660',
  ],
  'Ducati': [
    'Monster 937',
    'Scrambler Icon',
    'Scrambler Nightshift',
    'Hypermotard 698',
    'Panigale V2',
    'Panigale V4',
    'Streetfighter V2',
    'Streetfighter V4',
    'Multistrada V4',
  ],
  'Revolt Motors': [
    'RV400',
    'RV400 BRZ',
    'RV1',
  ],
  'Other': [
    'Other Model',
  ],
};

export const BIKE_BRANDS = Object.keys(INDIAN_BIKE_CATALOG);

export const COMMON_VARIANTS = [
  'Standard',
  'Dual Channel ABS',
  'Single Channel ABS',
  'Disc',
  'Drum',
  'Bluetooth / Connected',
  'Dark Edition / Black Edition',
  'Special Edition',
  'Alloy Wheel',
  'Spoke Wheel',
  'Top Model',
  'V2',
  'V3',
  'V4',
  'Base Model',
  'Custom',
];

export const CURRENT_YEAR = new Date().getFullYear();

export const YEAR_OPTIONS = Array.from({ length: 27 }, (_, i) => CURRENT_YEAR + 1 - i);

export const OWNER_OPTIONS = [
  { value: 1, label: '1st Owner' },
  { value: 2, label: '2nd Owner' },
  { value: 3, label: '3rd Owner' },
  { value: 4, label: '4th Owner' },
  { value: 5, label: '5+ Owners' },
];

export const CONDITION_OPTIONS = [
  'Mint Condition',
  'Like New',
  'Excellent',
  'Good',
  'Fair',
];

export const LOCATION_OPTIONS = [
  'Chennai, Tamil Nadu',
  'Coimbatore, Tamil Nadu',
  'Madurai, Tamil Nadu',
  'Trichy, Tamil Nadu',
  'Salem, Tamil Nadu',
  'Tirunelveli, Tamil Nadu',
  'Vellore, Tamil Nadu',
  'Erode, Tamil Nadu',
  'Kanchipuram, Tamil Nadu',
  'Tiruvallur, Tamil Nadu',
  'Chengalpattu, Tamil Nadu',
  'Other',
];
